In [1]:

import numpy as np
#create the 4x2 array of type unsigned int 16
#we use np.array() and specify the data type
my_array = np.array([[1,2],[3,4],[5,6],[7,8]],dtype=np.int16)

# print the attributes 
print("The shape of the Array is:",my_array.shape)
print("The number of dimensions is:",my_array.ndim)
print("The size of each element in bytes is:",my_array.itemsize)


The shape of the Array is: (4, 2)
The number of dimensions is: 2
The size of each element in bytes is: 2


In [2]:
#create 3x3 numpy array of all true 
#expected output:
#{[true true true]
#[true true true]
#[true true true]}

import numpy as np
arr = np.ones((3,3),dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
#extract the documentation of numpy arrange fun
import numpy as np
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

In [4]:
#create a 1d array filled with zeros and another filled with ones
#expected output
#zeros:[0,0,0,0,0]
#ones:[1,1,1,1,1]
import numpy as np
zeros_arr = np.zeros(5)
ones_arr = np.ones(5)
print("zeros:",zeros_arr)
print("ones:",ones_arr)

zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1. 1. 1.]


In [ ]:
#create a 1d array of 10 evenly spaced elements between 5 and 50
#expected output:
#[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
#syntax: np.linspace(start, stop, num)
import numpy as np
arr = np.linspace(5, 50, 10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [6]:
#find the memory size of numpy array of numbers from 0 to 9
#expected output:
#array:[0 1 2 3 4 5 6 7 8 9]
#Memory size of the array in bytes: 40 bytes
import numpy as np
arr = np.arange(10)
print("Array:", arr)
print("Memory size of the array in bytes:", arr.nbytes)

Array: [0 1 2 3 4 5 6 7 8 9]
Memory size of the array in bytes: 80


In [10]:
# reverse 1d numpy array 
import numpy as np
arr = np.arange(10)
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [11]:
#create a 3x3 identity matrix using numpy
import numpy as np
identity_matrix = np.eye(3) #eye function creates a 2-D array with ones on the diagonal and zeros elsewhere
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
#create a 4x4 array and extract its first row and last column
#expected output:
#first row: [1 2 3 4]
#last column: [ 4  8 12 16]
import numpy as np

arr = np.arange(1,17).reshape(4,4)
first_row = arr[0]
print("first row:", first_row)

last_column = arr[:, -1]
print("last column:", last_column)

first row: [1 2 3 4]
last column: [ 4  8 12 16]


In [4]:
# extract odd rows and even columns
#problem brakdown:
#rows: in programming, indexing starts from 0 odd-indexed rows would be 1 and 3
#columns: even-indexed columns would be 0 and 2
import numpy as np
#original array
samplearray = np.array([[3, 6, 9, 12],
                       [15, 18, 21, 24],
                       [27, 30, 33, 36], 
                       [39, 42, 45, 48]])

#using slicing to select odd rows and even columns
#the slice [1::2] selects every second element starting from index 1 (odd rows)
#the slice [0::2] selects every second element starting from index 0 (even columns)
newArray = samplearray[1::2, 0::2]
print("Original array:")
print(samplearray)
print("\nNew array with odd rows and even columns:")
print(newArray)

Original array:
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]]

New array with odd rows and even columns:
[[15 21]
 [39 45]]


In [7]:
# Stack Array horizontally
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
stacked_array = np.hstack((a, b))
print("Stacked array horizontally:", stacked_array)

Stacked array horizontally: [[1 2 5 6]
 [3 4 7 8]]


In [8]:
#stack array vertically
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
stacked_array = np.vstack((a, b))
print("Stacked array vertically:", stacked_array)

Stacked array vertically: [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# write a code to extact all numbers from an array that are between 4 and 10 inclusice
i
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
numbers = arr[(arr >= 4) & (arr <= 10)]

NameError: name 'np' is not defined